examples/gno.land/r/boards/README.md, gnoland/website/views/faucet.html
the PR can be merged right now, but if it stays open, I'll reuse it as soon as I
find new typos
=> chore: fix typos

examples/gno.land/r/boards/public.gno
Currently any user can delete a post.
=> boards: check post owner

examples/gno.land/r/boards/board.gno, examples/gno.land/r/boards/post.gno, examples/gno.land/r/boards/public.gno, examples/gno.land/r/boards/role.gno, tests/files2/zrealm_boards4.gno
=> feat: add EditPost feature

.github/workflows/examples.yml, Makefile, examples/gno.land/p/testutils/misc.gno
* test `gnodev precompile`
* test `gnodev build`
* fix invalid gno.land/p/testutils package (duplicate variable)
=> ci: test gnodev {precompile,build} against ./examples/ on CI

gnoland/docs/peace.md
hey, sorry for such a small change; but I was looking for a typo somewhere,
to let my appreciation and support in the git history forever.
=> peace(love): all my support

examples/gno.land/p/releases/changelog.gno, examples/gno.land/p/releases/release.gno, examples/gno.land/r/releases-example/dummy.gno, examples/gno.land/r/releases-example/example.gno, tests/files2/zrealm_releases0.gno, tests/files2/zrealm_releases1.gno
This PR implements a way to manage realm versioning.
=> feat: add a new gno.land/p/releases package

.gitpod.yml, misc/devdeps/Makefile
=> chore: update gitpod config

examples/gno.land/r/boards/README.md
=> chore: update getting started guide

cmd/gnodev/main.go, cmd/gnodev/repl.go, cmd/gnodev/test.go, cmd/gnodev/util.go
=> feat: basic 'gnodev repl' helper

cmd/gnodev/main_test.go
=> test(gnodev): add integration tests

cmd/gnodev/main_test.go, cmd/gnodev/test.go, tests/integ/failing1/failing.gno, tests/integ/failing1/failing_test.gno, tests/integ/failing2/failing.gno, tests/integ/failing2/failing_filetest.gno, tests/integ/minimalist-gno1/minim.gno, tests/integ/minimalist-gno2/minim.gno, tests/integ/minimalist-gno2/minim_test.gno, tests/integ/minimalist-gno3/minim.gno, tests/integ/minimalist-gno3/minim_filetest.gno, tests/integ/valid1/valid.gno, tests/integ/valid1/valid_test.gno, tests/integ/valid2/valid.gno, tests/integ/valid2/valid_filetest.gno
=> fix(gnodev): was using exit code 0 for some failing cases + add new integration tests

pkgs/sdk/vm/keeper_test.go
=> chore: fix tests

cmd/gnodev/test.go, cmd/gnodev/util_match.go
=> chore: support --run file/* for filetest.gno files

misc/staging.gno.land/Makefile
=> chore: update staging's makefile helpers for operations

.github/workflows/unit-tests.yml, Makefile, cmd/gnodev/main_test.go, cmd/gnodev/test.go, cmd/gnodev/util.go, cmd/gnoland/main.go, cmd/gnoland/main_test.go, pkgs/testutils/io.go
=> chore: add 'gnoland --skip-start’

.github/workflows/docker.yml, Dockerfile
=> chore: setup multistage docker

misc/staging.gno.land/docker-compose.yml
=> chore: fix staging deployment

misc/docker-build-stages.sh
=> chore: add misc/docker-build-stages

examples/gno.land/r/boards/README.md, examples/gno.land/r/boards/board.gno, examples/gno.land/r/boards/public.gno, examples/gno.land/r/boards/z_0_filetest.gno, examples/gno.land/r/boards/z_5_d_filetest.gno, examples/gno.land/r/boards/z_7_filetest.gno
Fix the issue we can not post on the board.
=> fixed CreatePost -> CreateThread issue

misc/staging.gno.land/overlay/config.toml
=> chore: setup CORS on staging

gnoland/website/HOME.md, gnoland/website/main.go, gnoland/website/views/home.html
=> chore: support custom home content

misc/staging.gno.land/docker-compose.yml, misc/staging.gno.land/overlay/HOME.md, misc/test2.gno.land/docker-compose.yml, misc/test2.gno.land/overlay/HOME.md
=> chore: update testnets infra

.github/workflows/unit-tests.yml, pkgs/bft/consensus/state_test.go
=> chore: mark ./pkgs/bft/consensus.TestStateHalt1 as flappy

cmd/gnoland/main.go, misc/test2.gno.land/.gitignore, misc/test2.gno.land/Makefile, misc/test2.gno.land/docker-compose.yml
=> chore: use independence-day's genesis for test2.gno.land

Dockerfile, misc/test2.gno.land/Makefile
=> chore: add gnotxport in the Docker image

.gitignore, misc/test2.gno.land/Makefile, misc/test2.gno.land/docker-compose.yml
=> chore(test2): setup TLS on rpc 36657

misc/test2.gno.land/overlay/config.toml
=> chore(test2): setup CORS headers

cmd/gnotxport/export.go
=> chore: increase verbosity of `gnotxport`

cmd/gnofaucet/README.md
Add an instruction to start the local faucet
=> chore: create faucet’s README.md

.github/workflows/build.yml, .github/workflows/db-tests.yml, .github/workflows/examples.yml, .github/workflows/unit-tests.yml, Dockerfile, go.mod
=> chore: bump go1.19

examples/gno.land/p/grc/grc20/dummy_test.gno, examples/gno.land/p/grc/grc20/grc20_test.gno
=> chore: add basic GRC20 tests

misc/test2.gno.land/docker-compose.yml
=> chore: bump test2's faucet to 50M

examples/gno.land/p/grc/exts/token_metadata.gno, examples/gno.land/p/grc/grc777/dummy_test.gno, examples/gno.land/p/grc/grc777/igrc777.gno
=> chore: add GRC777 interface

cmd/gnofaucet/gnofaucet.go, cmd/gnofaucet/throttle.go, misc/test2.gno.land/docker-compose.yml
* refactor logs
* refactor throttler
* configure test2 to run behind proxy
=> chore: fix faucet on test2

.dockerignore, .github/workflows/unit-tests.yml, Makefile, tests/docker-integration/README.md, tests/docker-integration/integration.go, tests/docker-integration/integration_test.go
=> chore: add docker-integration test

cmd/gnofaucet/README.md
* rename faucet to gnofaucet
* gnoland must start before gnofaucet
=> chore: update cmd/gnofaucet/README.md

examples/gno.land/r/faucet/admin.gno, examples/gno.land/r/faucet/faucet.gno, examples/gno.land/r/faucet/faucet_filetest.gno, examples/gno.land/r/faucet/faucet_test.gno, pkgs/std/coin.go, stdlibs/std/coins.gno, stdlibs/stdshim/coins.gen.go, stdlibs/stdshim/time.gen.go
=> feat: add r/faucet

Makefile, cmd/gnodev/build.go, cmd/gnodev/main.go, cmd/gnodev/main_test.go, cmd/gnodev/precompile.go, cmd/gnodev/repl.go, cmd/gnodev/test.go, precompile.go
=> chore: make 'gnodev test' precompile and build, except if '--no-precompile'

cmd/gnotxport/export.go
=> chore: make txport retry blocks for reliability

cmd/gnodev/util.go
=> chore: cleanup debug

pkgs/crypto/keys/client/broadcast.go
Example:
```sh
./build/gnokey broadcast createboard.signed.txt --remote test2.gno.land:36657 --dry-run 
```
> Current `--gas-wanted` requirement for CreateBoard is 3.2M instead 2M
=> Add Tx simulate option

.gitignore, examples/gno.land/r/foo20/foo20.gno, examples/gno.land/r/foo20/foo20_test.gno
=> chore(foo20): add faucet

stdlibs/stdlibs.go
=> feat: add std.DerivePkgAddr helper

cmd/gnoland/main.go, examples/gno.land/r/demo/types/types.gno, examples/gno.land/r/demo/types/types_test.gno
=> feat: add a r/demo/types package 

.gitignore, examples/gno.land/p/demo/flow/flow.gno, examples/gno.land/p/demo/gnode/gnode.gno, pkgs/gnolang/preprocess.go
=> chore: small chores

cmd/gnoland/main.go, examples/gno.land/r/system/rewards/rewards.gno, examples/gno.land/r/system/validators/validators.gno, misc/staging.gno.land/overlay/HOME.md
=> chore: various changes for test3

examples/gno.land/p/demo/blog/blog.gno, examples/gno.land/p/demo/blog/errors.gno, examples/gno.land/r/gnoland/blog/admin.gno, examples/gno.land/r/gnoland/blog/gnoblog.gno, examples/gno.land/r/gnoland/blog/util.gno
=> chore: improve blog realm

gnoland/website/HOME.md, misc/test3.gno.land/.env.example, misc/test3.gno.land/.gitignore, misc/test3.gno.land/Makefile, misc/test3.gno.land/README.md, misc/test3.gno.land/docker-compose.yml, misc/test3.gno.land/overlay/HOME.md, misc/test3.gno.land/overlay/config.toml
=> feat: test3

examples/gno.land/r/demo/boards/board.gno, examples/gno.land/r/demo/boards/post.gno, examples/gno.land/r/demo/boards/public.gno, examples/gno.land/r/demo/boards/render.gno, examples/gno.land/r/demo/boards/z_0_filetest.gno, examples/gno.land/r/demo/boards/z_10_c_filetest.gno, examples/gno.land/r/demo/boards/z_10_filetest.gno, examples/gno.land/r/demo/boards/z_11_d_filetest.gno, examples/gno.land/r/demo/boards/z_11_filetest.gno, examples/gno.land/r/demo/boards/z_1_filetest.gno, examples/gno.land/r/demo/boards/z_2_filetest.gno, examples/gno.land/r/demo/boards/z_3_filetest.gno, examples/gno.land/r/demo/boards/z_4_filetest.gno, examples/gno.land/r/demo/boards/z_5_c_filetest.gno, examples/gno.land/r/demo/boards/z_5_filetest.gno, examples/gno.land/r/demo/boards/z_6_filetest.gno, examples/gno.land/r/demo/boards/z_7_filetest.gno, examples/gno.land/r/demo/boards/z_8_filetest.gno, examples/gno.land/r/demo/boards/z_9_filetest.gno
=> chore: fix blog realm rendering

gnoland/website/static/css/app.css
New website design — Related to [PR 392](https://github.com/gnolang/gno/pull/392)
=> feat: new website design

misc/test3.gno.land/Makefile, misc/test3.gno.land/docker-compose.yml, misc/test3.gno.land/overlay/HOME.md
=> chore(test3): update homepage + update genesis

gnoland/website/static/css/app.css, gnoland/website/views/home.html
=> chore: remove fancy design from homepage

cmd/gnodev/main.go
- use "field:value" scheme in struct literal
- refactor: Make mainApp items more readable
=> gnodev: minor refactoring and lint error fixes

.github/dependabot.yml
This PR adds Dependabot weekly notifications for top level Go modules.
@moul @harry-hov 
We can probably discuss adding other maintainers with write access to the reviewers in the actual configuration file.
=> chore: add Dependabot support for top level go modules

pkgs/sdk/vm/keeper.go
Handle the panic error  in query functions and return the err msg
=> Show query eval error

gnoland/website/pages/ABOUT.md
=> fix grammer

examples/gno.land/p/demo/stack/stack.gno, examples/gno.land/p/demo/stack/stack_test.gno
This PR implements `p/demo/stack`
=> feat: implement p/demo/stack

Makefile, cmd/gnodev/main.go, cmd/gnodev/repl.go, cmd/gnodev/run.go
Extracted from #461 by @jaekwon
=> feat: gnodev run

cmd/gnodev/build_test.go, cmd/gnodev/main_test.go, cmd/gnodev/mod_test.go, cmd/gnodev/precompile_test.go, cmd/gnodev/repl_test.go, cmd/gnodev/run.go, cmd/gnodev/run_test.go, cmd/gnodev/test.go, cmd/gnodev/test_test.go, tests/integ/run-main/main.gno, tests/integ/run-namedpkg/main.gno
* gnodev: refactor streams and fix tests
* add new test for gnodev run
* split test main cases per command
=> chore: refactor gnodev integration tests

misc/deployments/staging.gno.land/docker-compose.yml, misc/deployments/test2.gno.land/docker-compose.yml, misc/deployments/test3.gno.land/docker-compose.yml
Fixes `docker compose up —build`.
=> chore: fix deployments' docker-compose.yml files

examples/gno.land/p/demo/ufmt/ufmt.gno, examples/gno.land/p/demo/ufmt/ufmt_test.gno, tests/files/switch41.gno
Fix #645
I also added a new case in `tests/files/switch41.gno` because there wasn't any scenario with a switch type and an interface.
=> fix(p/demo/ufmt): handle stringer interface

pkgs/gnolang/machine.go
=> WIP use constructor to reset fields while keeping alloc slice

Makefile
add simple Makefile rule 
```bash
$ make install
```
=> chore: add makefile rule install

.github/workflows/db-tests.yml, .github/workflows/docker.yml, .github/workflows/examples.yml, .github/workflows/gnoland.yml, .github/workflows/gnovm.yml, .github/workflows/misc.yml, .github/workflows/tm2.yml
h/t @thehowl and @zivkovicmilos
=> test: fix CI running on master

Makefile, misc/docker-integration/Makefile, misc/docker-integration/integration_test.go
This PR makes Docker more optional during development.
=> chore: make Docker more optional for devs

.github/workflows/gnovm.yml, gnovm/tests/files/zrealm_tests0.gno
First commit is to ensure we reproduce the master fail.
Second commit fix the failure.
=> test: fix master fail

tm2/Makefile
=> chore: fix typo in tm2 makefile

.github/codecov.yml, .github/workflows/examples.yml, .github/workflows/gnoland.yml, .github/workflows/gnovm.yml, .github/workflows/tm2.yml, gno.land/Makefile, gnovm/Makefile, tm2/Makefile
Add Codecov support for tm2, gnovm, gno.land.
Related to #572.
=> test: set up Codecov

.github/codecov.yml, .gitignore
=> chore: disable codecov status check

gnovm/tests/challenges/print_ref.gno
Adding a low-priority challenge.
=> chore: add gnovm/tests/challenges/print_ref.gno

README.md
Blocks https://github.com/avelino/awesome-go/pull/4914
=> chore: add badges in README

examples/gno.land/r/x/nir1218_evaluation_proposal/EVALUATION.md
Fixed a few typos as I read this
=> chore: fix typos in nir1218_evaluation_proposal/EVALUATION.md

gno.land/LICENSE.md, gnovm/LICENSE.md
Please provide a detailed description of the changes made in this pull request.
</details>
=> Fix gno.land additional terms

examples/gno.land/p/demo/ufmt/ufmt.gno
=> docs(p/demo/ufmt): add documentation to package and Sprintf

gnovm/pkg/gnolang/ownership.go
Adding doc to `Object::GetIsReal()` based on an explanation from @jaekwon
=> docs: add doc for GetIsReal

tm2/pkg/commands/utils.go
fixes #1060 (maybe). @ekleiner to verify :)
=> fix(pkg/commands): readPassword support for windows

.github/codecov.yml
See https://github.com/gnolang/gno/pull/1078#pullrequestreview-1625492448
Frankly, I'm always cautious when working with configuration files that can only be fully validated after merging and opening a new PR.
I've consulted the documentation and also referenced popular codecov files from other repositories for guidance.
Reference: https://docs.codecov.com/docs/codecovyml-reference
=> chore: update codecov.yml

PHILOSOPHY.md
Based on https://github.com/tendermint/tendermint/pull/3034
=> chore: update PHILOSOPHY.md

.github/workflows/monthly-snapshots.yml
=> ci: add workflow for automatic monthly snapshots

gno.land/cmd/gnoweb/views/funcs.html, misc/deployments/staging.gno.land/docker-compose.yml
- enable analytics on staging
- switch to custom domain
=> chore: enable analytics on staging

examples/gno.land/r/demo/groups/README.md
=> fix: -broadcast true in doc

gnovm/cmd/gno/lint.go, gnovm/cmd/gno/lint_test.go
=> fix(cmd/gno): change set_exit_stauts flag to kebab-case

misc/loop/go.mod, misc/loop/go.sum
Upgrade loop version for tx-archive
</details>
=> chore(misc/loop): upgrade tx-archive to v0.1.1

examples/gno.land/r/gnoland/home/home.gno, examples/gno.land/r/gnoland/home/home_filetest.gno
=> chore: portal loop's homepage update

docs/overview.md
This PR updates the documentation overview file, referencing the [Diataxis](https://diataxis.fr) framework we are using and explaining how to use the docs efficiently. 
</details>
=> docs: update docs overview

docs/reference/go-gno-compatibility.md, docs/reference/rpc-endpoints.md, docs/reference/standard-library.md
This PR fixes some typos in the documentation.
=> docs: fix some typos

docs/overview.md, misc/docusaurus/src/css/custom.css
Add a meta description for the main page and should fix the fix of the navbar (would be awesome to get a deploy preview for docs related PR).
=> style: fix navbar and add better meta description

gnovm/pkg/gnolang/nodes.go, gnovm/stdlibs/std/native.go
=> chore: remove leftover debugging printlns

PHILOSOPHY.md
Following discussion on review call
=> docs(PHILOSOPHY): update philosophy on short flags

.github/dependabot.yml
This PR introduces [dependabot PR grouping](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups), based on historical single PRs in the repo.
</details>
=> feat: add Dependabot groups

tm2/pkg/bft/rpc/lib/server/handlers.go
=> chore(bft/rpc): fix typo in handlers.go

examples/gno.land/r/gnoland/home/home_filetest.gno
muscle memory ignored the failing CI due to bft once again...
=> chore(examples): fix tests

.github/workflows/gnoland.yml, .github/workflows/gnovm.yml, .github/workflows/misc.yml, .github/workflows/tm2.yml
- adds actions/checkout to upload-coverage actions, so that codecov can find the configuration file (could just be a sparse-checkout, but I think a checkout is cheap anyway so it shouldn't matter)
- fixes up misc
=> ci(codecov): fix configuration

examples/gno.land/p/demo/blog/blog.gno, examples/gno.land/r/gnoland/blog/admin.gno, examples/gno.land/r/gnoland/home/home.gno, examples/gno.land/r/gnoland/home/home_filetest.gno
This PR updates the blog widget render on the home page by making it show sorted blogs, as well as a condition and a small update to the title.
</details>
=> chore(blog): make blog widget better

examples/gno.land/r/gnoland/pages/page_events.gno
This PR introduces a small fix to the events page requested by marketing.  
- [x ] Added references to related issues and PRs
</details>
=> fix(gno.land): update nebular text

examples/gno.land/p/demo/memeland/memeland.gno, examples/gno.land/p/demo/memeland/memeland_test.gno
Added a few checks to the sorting of posts for Memeland. 
</details>
=> chore(memeland): add sorting condition

doc.go
- update copyright, license
- add ascii banner (for `go doc`, and `godoc`)
</details>
=> chore: update /doc.go

docs/concepts/portal-loop.md
Adds a bit more clarification on how the Portal Loop works.
</details>
=> docs(Portal Loop): add more info to Portal Loop concepts page

gnovm/pkg/gnolang/machine.go
=> fix: add heads machine string

gno.land/cmd/gnoland/genesis_balances_add.go, gno.land/cmd/gnoland/genesis_balances_remove.go, gno.land/cmd/gnoland/genesis_validator_add.go, gno.land/cmd/gnoland/genesis_validator_remove.go
=> chore(cmd/gnoland): `s/LongHelp/ShortHelp` in genesis commands

.github/workflows/examples.yml, examples/gno.land/r/x/test_prev/gno.mod
Added a new PR into master without rebasing it first. Fixing failing test.
=> fix(ci): failing `examples/mod-tidy`

examples/gno.land/r/gnoland/pages/page_events.gno
This PR adds the Golang Serbia Gno meetup to the "Upcoming events" page on `gnoweb`.
</details>
=> chore: add Golang Serbia meetup to events page

.github/workflows/releaser.yml
=> fix: Change goreleaser secret name

misc/loop/cmd/snapshotter.go, misc/loop/scripts/start.sh
=> fix(misc/loop): fix portal loop post goreleaser

misc/loop/cmd/snapshotter.go
=> fix(misc/loop): edit volume path

docs/concepts/testnets.md, examples/gno.land/r/gnoland/home/home.gno, examples/gno.land/r/gnoland/home/home_filetest.gno
Closes [#2121](https://github.com/gnolang/gno/issues/2121)
</details>
=> feat(docs/home): Add Faucet Hub & `gno.land/faucet` mentions

docs/reference/stdlibs/std/coins.md
=> fix(docs): update a typo in coins.md

examples/gno.land/r/demo/userbook/userbook.gno
This PR adds a `SignUp` event emit in the Userbook realm, as well as some more comments.
</details>
=> chore(examples): add event emit to Userbook realm

docs/how-to-guides/creating-grc20.md
Description:
While helping someone on Discord who had an `issue` with the [gcr20 tutorial](https://docs.gno.land/how-to-guides/creating-grc20), I took the liberty of suggesting modifications to fix the problem for future users
=> docs: fix code in creating-grc20.md

.benchmarks/README.md, docs/concepts/effective-gno.md, examples/gno.land/p/demo/cford32/README.md, examples/gno.land/p/demo/cford32/cford32.gno
Some minor typos I encountered while browsing the repo :smile: 
</details>
=> style: Fixing some typos

docs/overview.md
=> docs: update `overview.md`

examples/gno.land/r/gnoland/events/events.gno, examples/gno.land/r/gnoland/events/events_filetest.gno
This PR updates the events page.
Soon, we will have a `r/gnoland/events` realm that will simplify this process of updating events through the CLI, instead of having to make a PR every time. There is an open issue on this somewhere but I cannot seem to find it.
</details>
=> chore(pages/events): update events

contribs/gnodev/pkg/dev/node.go
=> chore(gnodev): fix typo

docs/reference/stdlibs/std/testing.md, gnovm/tests/stdlibs/std/std.gno
This PR adds `TestSetRealm` docs, as well as related docs. It also fixes up a few minor details. 
Closes: #2273 
</details>
=> docs: add `TestSetRealm` reference docs

examples/gno.land/r/x/manfred_upgrade_patterns/upgrade_c/v2/v2.gno, examples/gno.land/r/x/manfred_upgrade_patterns/upgrade_d/v2/v2.gno, examples/gno.land/r/x/manfred_upgrade_patterns/upgrade_d/v2/z_filetest.gno
Small fix to correct the version number in upgrade demo.
=> fix(examples): correct the version number in upgrade demo

examples/gno.land/r/demo/bar20/gno.mod
</details>
Update /r/demo/bar20/gno.mod because of failing pipeline
=> fix(examples): update /r/demo/bar20/gno.mod

examples/gno.land/r/gnoland/home/home_filetest.gno
=> chore(test):  update home_filetest.gno due to CI failed

LICENSE.md, docs/concepts/effective-gno.md, docs/concepts/stdlibs/gnopher-hole.md, docs/how-to-guides/creating-grc20.md, examples/gno.land/r/gnoland/pages/page_license.gno
=> docs: fix typos

misc/deployments/test4.gno.land/genesis.json, misc/deployments/test4.gno.land/genesis_balances.txt
This PR adds:
- Iker Gno key address
- DevX Faucets addresses
- DevX Validators
</details>
=> feat: add devx balances and validators

misc/deployments/test4.gno.land/genesis.json
Adds onbloc validator into test4 genesis.
=> feat: add onbloc validator

.github/workflows/portal-loop.yml
The CI workflow was missing `/**` in its syntax
=> ci(portal-loop): run workflow on all changes to misc/loop

examples/gno.land/r/demo/wugnot/wugnot.gno
-> https://github.com/gnolang/gno/pull/2537
=> chore: fix broken CI

misc/deployments/test4.gno.land/README.md, misc/deployments/test4.gno.land/config.toml
This PR adds the recommended persistent peers for `test4.gno.land`.
</details>
=> chore: add test4 `persistent_peers`

.github/ISSUE_TEMPLATE/BUG-REPORT.md, gnovm/cmd/gno/bug.go
Update bug template to be consistent with each other
=> refactor(gnovm/gno/bug): sync bug template

gnovm/cmd/gno/bug_test.go
=> test(cmd/gno): fix TestBugApp

misc/deployments/test4.gno.land/README.md, misc/deployments/test4.gno.land/config.toml
=> chore(test4): add teritori persistent peer

gno.land/cmd/gnoland/testdata/gnoweb_airgapped.txtar
=> chore: fix ci

examples/gno.land/r/demo/art/millipede/millipede.gno, examples/gno.land/r/demo/art/millipede/millipede_test.gno
</details>
During a Office hour call in Discord, we have see a error for `r/demo/art/millipede` 
cc @leohhhn
=> fix: wrong url syntax 

docs/gno-tooling/cli/gnokey/querying-a-network.md
This PR adds more info for the `vm/qfile` query.
</details>
=> docs(gnokey): add more info on `vm/qfile`

.gitattributes
=> chore: mark files generated from genstd as generated

gno.land/cmd/gnoland/testdata/restart_missing_type.txtar
=> test(gno.land): fix `TestTestdata/restart_missing_type`

.github/workflows/benchmark-master-push.yml
=> ci(hotfix): yaml whitespace

examples/gno.land/r/gnoland/pages/page_contribute.gno
Added the gno.land grants GH repository link to the page
=> chore(gnoweb): update page_contribute.gno

examples/gno.land/p/demo/json/README.md
in the three examples provided in the README.md file, there's a useless import of "fmt" package.
</details>
=> fix: Update json package README.md

.github/workflows/benchmark-master-push.yml
Just reduce commits then could trigger benchmarks
=> chore(ci): reducing folders spinning up benchmarks

examples/gno.land/r/gnoland/pages/page_contribute.gno
By internal request.
</details>
=> chore(pages): update bounty Terms & Conditions link

.github/codecov.yml
The change does not appear to be applied to my PR #2920, so I am opening a dedicated PR to make Codecov aware.
=> chore(codecov): ignore generated files

.github/goreleaser.yaml, .github/workflows/releaser-nightly.yml, .github/workflows/releaser.yml
=> ci: fixup goreleaser workflow, again

.github/goreleaser.yaml, .github/workflows/releaser-master.yml, .github/workflows/releaser-nightly.yml, .github/workflows/releaser.yml
=> ci: fix goreleaser ci again again

misc/deployments/test5.gno.land/config.toml, misc/deployments/test5.gno.land/genesis.json, misc/deployments/test5.gno.land/genesis_balances.txt
=> feat: test5 validators and faucets devx

misc/deployments/test5.gno.land/config.toml, misc/deployments/test5.gno.land/genesis.json, misc/deployments/test5.gno.land/genesis_balances.txt
=> feat: teritori test5 validator, peer and genesis balances

examples/README.md
Updates the examples README.
</details>
=> chore(examples): update README

.github/workflows/autocounterd.yml, misc/loop/docker-compose.override.prod.yml
small fixes to portal loop prod config and autocounterd build
=> chore: (portal loop): Fixing Portal loop prod config

examples/gno.land/r/demo/boards2/board.gno, examples/gno.land/r/demo/boards2/board_test.gno, examples/gno.land/r/demo/boards2/boards.gno, examples/gno.land/r/demo/boards2/format.gno, examples/gno.land/r/demo/boards2/gno.mod, examples/gno.land/r/demo/boards2/post.gno, examples/gno.land/r/demo/boards2/post_test.gno, examples/gno.land/r/demo/boards2/public.gno, examples/gno.land/r/demo/boards2/render.gno, examples/gno.land/r/demo/boards2/role.gno
Use correct package name for boards2 realm.
</details>
@jeronimoalbi
=> feat(boards2): update package name to boards2

tm2/pkg/p2p/netaddress.go, tm2/pkg/sdk/baseapp.go
=> chore: fix some function names in comment

gno.land/pkg/sdk/vm/keeper.go, gnovm/pkg/gnolang/realm.go, gnovm/pkg/gnolang/store.go, gnovm/pkg/gnolang/store_test.go, gnovm/pkg/gnolang/values.go, gnovm/pkg/test/imports.go, gnovm/stdlibs/stdlibs.go, gnovm/tests/stdlibs/stdlibs.go
It's not a "store", this was a misnomer from the beginning.
=> chore: s/NativeStore/NativeResolver/g

misc/deployments/test4.gno.land/README.md, misc/deployments/test5.gno.land/README.md
I reviewed the entire repository, no more typos found in docs. 
Hope this helps streamline the project!
Best regards,
Bilogweb3
=> chore: correct typos docs

examples/gno.land/p/demo/avl/pager/pager.gno, examples/gno.land/p/demo/avl/pager/pager_test.gno, examples/gno.land/p/demo/avl/pager/z_filetest.gno, examples/gno.land/r/demo/userbook/render.gno, examples/gno.land/r/demo/userbook/userbook.gno, examples/gno.land/r/demo/users/users.gno, examples/gno.land/r/docs/avl_pager/avl_pager.gno, examples/gno.land/r/leon/hof/render.gno
This PR adds the reverse option in the avl_pager package, and updates the rendering in the `r/demo/userbook` realm. 
</details>
=> feat(examples): add avl_pager reverse option, update userbook

docs/reference/stdlibs/std/chain.md
Adds the reference docs on `std.ChainDomain()`.
</details>
=> docs: add `std.ChainDomain()` reference

gnovm/pkg/gnolang/preprocess.go, gnovm/tests/files/native0.gno
trying to avoid reports like #3361
=> chore(gnovm): add suggestion to build for bodyless funcs error

gnovm/pkg/benchops/exporter.go
=> fix(benchops): support 32-bit compilation

examples/gno.land/r/nemanya/config/config.gno, examples/gno.land/r/nemanya/config/gno.mod, examples/gno.land/r/nemanya/home/gno.mod, examples/gno.land/r/nemanya/home/home.gno
This home realm allows users to donate GNOT to support Web3 projects, with dynamic content updates, text art, and a sponsor leaderboard. The code is easy to understand and copy, making it a great example. It also serves as an informative introduction to myself for ecosystem users.
- **Text Art Rendering:**
- Introduced a feature to display text art in codeblocks, offering a visually appealing and customizable way to present content on the home realm page.
- **Content Customization:**
- Admin can easily update the contents of the page, including sections like "About Me," "Sponsor Information," and social media links, giving them full control over the realm’s presentation.
- **GNOT Donation System for Projects:**
- Integrated a GNOT donation system, enabling users to sponsor specific Web3 …
=> feat(examples): Add Nemanya's Home Realm to Examples

examples/gno.land/p/moul/ulist/gno.mod, examples/gno.land/p/moul/ulist/ulist.gno, examples/gno.land/p/moul/ulist/ulist_test.gno
Replaces #3402 
Related with #3321
=> feat(examples): add moul/ulist

examples/gno.land/r/stefann/home/home.gno, examples/gno.land/r/stefann/home/home_test.gno
Changes in the home realm:
- Convert `HTML` to pure `.md`
- Register the realm in `HoF`
- Add namespace resolution functionality
- Implement `ugnot` to `gnot` conversion for Leaderboard
- Update tests
=> feat(stefann/home): Convert HTML to Markdown and enhance features

gno.land/cmd/gnoland/start.go
Increase the block gas limit accordingly as we update the gas configuration.
=> fix: increase max block gas limit

gnovm/pkg/transpiler/fuzz_test.go
cc/ @odeke-em
Fixes master CI.
=> test: fix adding examples directory in fuzzer

contribs/github-bot/internal/config/config.go
- change the "docs" merge requirements to allow also for a third-party contribution approved by both core+devrel
- disallow merging on all prs with the "don't merge" label
- don't require additional information on dependabot PRs
=> feat(github-bot): config improvements

examples/gno.land/r/demo/boards2/format.gno, examples/gno.land/r/demo/boards2/post.gno, examples/gno.land/r/demo/boards2/post_test.gno, examples/gno.land/r/demo/boards2/public.gno
Based on https://github.com/gnolang/gno/pull/3469
Closes: https://github.com/gnolang/gno/issues/3227
=> feat(boardsv2): initialize reposting

gno.land/pkg/integration/pkgloader.go, gno.land/pkg/integration/testdata/issue_3546.txtar
=> fix(txtar): ignore filetests when loading packages

examples/gno.land/r/gnoland/pages/page_contribute.gno
I added the bounties repo link to this page.
=> chore(r/gnoland/pages): add bounties repo link to `page_contribute.gno`

tm2/pkg/p2p/switch.go
This fixes an infinite loop if no peers are in the dial queue.
=> fix(p2p): infinity loop if no peer in queue

examples/gno.land/r/nt/boards2/public.gno, examples/gno.land/r/nt/boards2/z_5_a_filetest.gno, examples/gno.land/r/nt/boards2/z_5_b_filetest.gno, examples/gno.land/r/nt/boards2/z_5_c_filetest.gno
Add missing filetests for `RemoveMember()` function.
- Success removing a realm member
- Fail for non member (unauthorized)
- Fail w/ unexisting user
=> test(boards2): add missing filetests for member removal

examples/gno.land/r/nt/boards2/z_4_a_filetest.gno, examples/gno.land/r/nt/boards2/z_4_b_filetest.gno, examples/gno.land/r/nt/boards2/z_4_c_filetest.gno, examples/gno.land/r/nt/boards2/z_4_d_filetest.gno, examples/gno.land/r/nt/boards2/z_4_e_filetest.gno, examples/gno.land/r/nt/boards2/z_4_h_filetest.gno
Add missing filetests for `ChangeMemberRole()` function.
- Successful role change for realm member
- Successful role change for board member
- Fail for an admin removing an owner role
- Fail for an admin changing a role to owner
- Success changing a role to owner by another owner
- Fail when role doesn't exist
- Fail when user is not found
- Fail for non member (unauthorized)
=> test(boards2): add missing filetests for member role change

examples/gno.land/r/nt/boards2/public.gno, examples/gno.land/r/nt/boards2/z_6_a_filetest.gno, examples/gno.land/r/nt/boards2/z_6_b_filetest.gno
Add missing filetests for`HasMemberRole()` and `IsMember()` functions.
- Successfully check valid member
- Successfully check non member
=> test(boards2): add missing filetests for member check

examples/gno.land/r/nt/boards2/z_15_a_filetest.gno, examples/gno.land/r/nt/boards2/z_15_b_filetest.gno, examples/gno.land/r/nt/boards2/z_15_c_filetest.gno, examples/gno.land/r/nt/boards2/z_15_d_filetest.gno
* Add `CreateRepost` tests:
* sequential repost
* repost flagged
Related to: https://github.com/gnolang/gno/issues/3623
CC @salmad3 @jeronimoalbi
=> feat(boards2): repost tests

examples/gno.land/r/leon/hof/datasource_test.gno, examples/gno.land/r/leon/hof/render.gno
Fixes rendering order in the hall of fame realm.
=> fix(examples): hall of fame render order

.github/goreleaser.yaml, Dockerfile.release
Adding support for Gnodev Docker image in Goreleaser
=> chore: introducing Gnodev official Docker image

.github/goreleaser.yaml, Dockerfile.release
Adding Stdlib to Gnodev Docker image
=> chore: Adding Stdlib to Gnodev Docker image

docs/concepts/namespaces.md, docs/concepts/testnets.md, docs/reference/network-config.md
=> docs: archive test4

gno.land/pkg/sdk/vm/msgs.go, gno.land/pkg/sdk/vm/msgs_test.go, gnovm/pkg/gnolang/helpers.go, gnovm/pkg/gnolang/preprocess.go
continuation of #3774, fixes #2190.
=> feat(sdk/vm): disallow calling internal realms

docs/concepts/testnets.md, docs/reference/gno-js-client/gno-provider.md, docs/reference/network-config.md, docs/reference/tm2-js-client/Provider/json-rpc-provider.md, docs/reference/tm2-js-client/Provider/ws-provider.md
Removes `staging` from the docs.
=> chore(docs): rm mentions of staging testnet

examples/gno.land/r/docs/minisocial/v2/admin.gno, examples/gno.land/r/docs/minisocial/v2/posts.gno, examples/gno.land/r/docs/minisocial/v2/posts_test.gno
The pager was not being reset upon post resetting the app.
=> fix(minisocial): reset pager upon reset

examples/gno.land/r/nt/boards2/v1/format.gno, examples/gno.land/r/nt/boards2/v1/permissions_default.gno, examples/gno.land/r/nt/boards2/v1/z_0_h_filetest.gno, examples/gno.land/r/nt/boards2/v1/z_3_f_filetest.gno, examples/gno.land/r/nt/boards2/v1/z_3_g_filetest.gno, examples/gno.land/r/nt/boards2/v1/z_3_i_filetest.gno
This PR updated `boards2` realm to work with the new users realm.
=> fix(boards2): change realm to work with new users realm

examples/gno.land/r/docs/docs.gno, examples/gno.land/r/docs/users/gno.mod, examples/gno.land/r/docs/users/resolve.gno
Adds a simple example on how to resolve names and addresses using the new user registry system. Also needed for a blog post.
=> feat(r/docs): using `r/sys/users`

docs/resources/gno-stdlibs.md
Updated the docs to reflect the changes from PR #3582
P.S.: I think it would be better to separate the `std` and `testing` functions into separate documents.
P.S.2: For lint errors, I really can't figure it out how to fix this with failure logs
=> docs: Update `gno-stdlibs` Testing Function Signatures

contribs/gnodev/cmd/gnodev/app_config.go, contribs/gnodev/cmd/gnodev/command_local.go, contribs/gnodev/cmd/gnodev/command_staging.go, contribs/gnodev/cmd/gnodev/main.go, contribs/gnodev/pkg/packages/resolver_root.go
This PR mostly improves `gnodev` internal documentation and adds some small "quality of life" improvements based on feedback I received from various people.
cc @n2p5 @sw360cab @leohhhn
=> chore(gnodev): improve QoL and Docs

CONTRIBUTING.md
Also fix `makeprg` usage which was not updated since the move of `gno lint` to `gno tool lint`.
Note that jdkato/gnols is still mentionned for Sublime Text. This file [0] should be updated in order to replace it with `gnoverse/gnopls`
[0] https://github.com/gnoverse/gnopls/blob/main/doc/subl.md
=> docs: replace jdkato/gnols by gnoverse/gnopls for vim-lsp config

examples/gno.land/r/gnoland/boards2/v1/board.gno, examples/gno.land/r/gnoland/boards2/v1/board_test.gno, examples/gno.land/r/gnoland/boards2/v1/permissions_default.gno, examples/gno.land/r/gnoland/boards2/v1/permissions_default_test.gno, examples/gno.land/r/gnoland/boards2/v1/post.gno, examples/gno.land/r/gnoland/boards2/v1/post_test.gno, examples/gno.land/r/gnoland/boards2/v1/public.gno, examples/gno.land/r/gnoland/boards2/v1/render.gno, examples/gno.land/r/gnoland/boards2/v1/z_4_g_filetest.gno
Changes:
- Validate input addresses to avoid invalid strings
- Change TX links so they trigger Adena wallet input fields
- Fix broken permissions unit test
=> chore(boards2): address `v1rc1` review issues

examples/gno.land/r/demo/demo.gno, examples/gno.land/r/demo/gno.mod
Adds a root package to r/demo to list items manually until #3518 is done.
=> feat: `r/demo` list page

examples/gno.land/p/gnoland/commondao/commondao.gno, examples/gno.land/p/gnoland/commondao/doc.gno, examples/gno.land/p/gnoland/commondao/proposal.gno, examples/gno.land/p/gnoland/commondao/proposal_test.gno, examples/gno.land/p/gnoland/commondao/record.gno, examples/gno.land/p/gnoland/commondao/record_test.gno, examples/gno.land/r/gnoland/commondao/z_5_a_filetest.gno
- Improves some slice initializations and function docs
- Limits the number of custom proposal vote choices
- Changes voting record to support pagination
- Adds initial `commondao` package documentation
=> feat(commondao): minor improvements

contribs/gnogenesis/internal/balances/balances_add.go
This PR updates the output of `gnogenesis balances add`, to respect the `std.Coins` formatting.
```shell
57 pre-mines saved
g14da4n9hcynyzz83q607uu8keuh9hwlv42ra6fa:{[171 123 89 150 248 36 200 33 30 32 211 253 206 30 217 229 203 119 125 149] [{%!d(string=ugnot) 10000000000}]}ugnot
g1f977l6wxdh3qu60kzl75vx2wmzswu68l03r8su:{[73 125 239 233 198 109 226 14 105 246 23 253 70 25 78 216 160 238 104 255] [{%!d(string=ugnot) 10000000000}]}ugnot
g13m7f2e6r3lh3ykxupacdt9sem2tlvmaamwjhll:{[142 252 149 103 67 143 239 18 88 220 15 112 213 150 25 218 151 246 111 189] [{%!d(string=ugnot) 10000000000}]}ugnot
g16ja66d65emkr0zxd2tu7xjvm7utthyhpej0037:{[212 187 173 55 84 206 236 55 136 205 82 249 227 73 155 247 22 187 146 225] [{%!d(string=ugnot) 10000000000}]}ugnot …
```
=> fix: update `gnogenesis balances add` output

.dockerignore, .github/workflows/docker-bake.yml, Dockerfile.new, Dockerfile.release, misc/deployments/bake/README.md, misc/deployments/bake/docker-bake.hcl
=> chore: Docker Bake adding support to (tentative)

examples/gno.land/r/docs/minisocial/v1/posts.gno
=> chore: add txlink to minisocial

misc/deployments/test6.gno.land/README.md, misc/deployments/test6.gno.land/config.toml, misc/deployments/test6.gno.land/generate.sh
Adding Core Team information for Test6 genesis.
=> feat: Gno Core Team genesis data for `test6`

misc/deployments/test6.gno.land/generate.sh
=> chore(test6): add devx validators

.github/workflows/testnets_build.yml
invalid syntax in github action
=> chore: fixing bake action

docs/builders/become-a-gnome.md, docs/builders/deploy-packages.md, docs/builders/local-dev-with-gnodev.md, docs/resources/gno-packages.md, docs/resources/gno-stdlibs.md, docs/users/interact-with-gnokey.md, examples/gno.land/r/gnoland/home/home.gno, examples/gno.land/r/gnoland/home/home_filetest.gno, misc/docs/tools/linter/links.go, misc/docs/tools/linter/main_test.go
Fixes a bug in the docs linter, and fixes the remaining broken links.
=> docs: fix broken links & sections, fix linter edge case

CONTRIBUTING.md, docs/builders/example-minisocial-dapp.md, docs/resources/go-gno-compatibility.md, examples/Makefile, gnovm/cmd/gno/README.md, gnovm/cmd/gno/main.go, gnovm/cmd/gno/testdata/lint/bad_import.txtar, gnovm/cmd/gno/testdata/lint/file_error.txtar, gnovm/cmd/gno/testdata/lint/issue_3930.txtar, gnovm/cmd/gno/testdata/lint/no_error.txtar, gnovm/cmd/gno/testdata/lint/no_gnomod.txtar, gnovm/cmd/gno/testdata/lint/not_declared.txtar, gnovm/cmd/gno/tool.go, gnovm/cmd/gno/tool_lint_test.go
=> chore: move 'gno tool lint' to 'gno lint'

gnovm/pkg/gnolang/nodes.go, gnovm/tests/files/declared_type.gno, gnovm/tests/files/declared_type_func.gno
=> fix(gnovm): fix decl for func with declared type

misc/deployments/test6.gno.land/README.md, misc/deployments/test6.gno.land/generate.sh
This PR updates the test6 genesis generation script, and checksums, to accommodate for latest GovDAO fixes by @ajnavarro on `master`.
=> chore: update test6 README and gen script

contribs/README.md
=> chore: update contribs/README.md

examples/gno.land/p/leon/coinsort/coinsort.gno, examples/gno.land/p/leon/coinsort/coinsort_test.gno, examples/gno.land/p/leon/coinsort/gno.mod
Adds a small `std.Coins` sort by balance or custom less func `p/` helper.
=> feat(examples): add small Coins sorting package

contribs/gnodev/pkg/dev/node_state_test.go, contribs/gnodev/pkg/dev/node_test.go, contribs/gnodev/pkg/packages/resolver_test.go, contribs/gnodev/pkg/proxy/path_interceptor_test.go
Fix forgotten gnodev tests that are breaking due to xform2 #4316 PR
=> fix(gnodev): xform2 breaking tests

misc/deployments/test6.gno.land/README.md, misc/deployments/test6.gno.land/generate.sh
This PR updates the test6 `README`, as well as the genesis generation script.
=> chore: update test6 `README` and `generate.sh`

gno.land/pkg/integration/testdata/govdao_proposal_only_members_proposals.txtar
=> fix(govdao): repair tests

.github/goreleaser.yaml
This PR updates the master goreleaser, following changes in #4503
=> fix: update master `goreleaser.yaml`

gnovm/pkg/gnolang/preprocess.go
maxwell's request from https://github.com/gnolang/gno/pull/4521#discussion_r2217817281
=> chore(gnovm): add clarifying comment in evalStaticType{,OfRaw}

misc/deployments/test7.gno.land/CHECKLIST.md, misc/deployments/test7.gno.land/README.md, misc/deployments/test7.gno.land/config.toml, misc/deployments/test7.gno.land/generate.sh
This PR adds the `test7` deployment to `misc/deployments`
=> feat: add initial `test7` deployment

docs/resources/gnoland-networks.md, examples/gno.land/r/gnoland/home/home.gno, examples/gno.land/r/gnoland/home/home_filetest.gno
`gnoland-networks.md` test7 description may be completed with precise additions.
=> chore(docs): update test6 to test7

contribs/gnodev/pkg/emitter/static/hotreload.js
It resolves issue #4089
cancel reload when search realms
Evedence
https://jam.dev/c/74bbcc68-a582-4daa-9b87-522915b21f47
=> fix(gnodev): #4089

CONTRIBUTING.md
=> docs: simplify CONTRIBUTING.md

gnovm/pkg/gnolang/frame.go
=> fix: keep number of defer on a local variable

gnovm/pkg/gnolang/garbage_collector.go
=> fix(garbage_collector): Ineffective overflow protection

examples/gno.land/r/gnoland/boards2/v1/public_invite.gno, examples/gno.land/r/gnoland/boards2/v1/render.gno, examples/gno.land/r/gnoland/boards2/v1/uris_board.gno, examples/gno.land/r/gnoland/boards2/v1/z_0_j_filetest.gno, examples/gno.land/r/gnoland/boards2/v1/z_ui_2_a_filetest.gno, examples/gno.land/r/gnoland/boards2/v1/z_ui_2_b_filetest.gno, examples/gno.land/r/gnoland/boards2/v1/z_ui_2_c_filetest.gno, examples/gno.land/r/gnoland/boards2/v1/z_ui_2_e_filetest.gno
PR restores changes from #4743
=> chore(boards2): restore board request invite link
